@startuml

       ' remove the spot
       hide circle
       ' avoid problems with angled crows feet
       skinparam linetype ortho
       ' font
       skinparam defaultFontName Arial

       ' define styles
       !define desc(x) <color:gray>(x)</color>
       !define refers(x) <i><color:green>x</color></i>
       !define FK(x) <color:#424897><<FK>></color>  x<color:#000></color>
       !define PK(x) <color:#973A4A><<PK>></color> x : INTEGER desc(generated)

       title Database ERD

       header New Bank
       footer Group 5

       entity "Customer" {
        PK(Id)
        --
        *FirstName : VARCHAR
        *LastName : VARCHAR
        *DOB : DATETIME
        *CreatedOn : DATETIME
       }



       entity "Ledger" {
        PK(Id)
        --
        *FK(FromAccountID) : INTEGER refers(Customer.Id)
        *FK(ToAccountID) : INTEGER refers(Customer.Id)
        *Amount : DOUBLE
        *CommittedOn : DATETIME
       }

       entity "AccountTypes" {
        PK(Id)
        --
        *(AccountType) : VARCHAR
        *InterestRate : INTEGER
       }

       entity "Accounts" {
        PK(Id)
        --
        *FK(CustomerID) : INTEGER
        *FK(AccountTypeID) : INTEGER
        *Balance : DOUBLE
       }


       ' relationships
       Customer ||--|{ Accounts
       AccountTypes ||--|{ Accounts
       Ledger }|--|{ Accounts

       @enduml